//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompetenceSet
    {
        public CompetenceSet()
        {
            this.CompetenceSet1 = new HashSet<CompetenceSet>();
            this.UserGroup = new HashSet<UserGroup>();
            this.password = new HashSet<password>();
        }
    
        public int CompetenceID { get; set; }
        public Nullable<int> CompetenceParentID { get; set; }
        public string CompetenceName { get; set; }
        public int OrderID { get; set; }
        public bool Valid { get; set; }
    
        public virtual ICollection<CompetenceSet> CompetenceSet1 { get; set; }
        public virtual CompetenceSet CompetenceSet2 { get; set; }
        public virtual ICollection<UserGroup> UserGroup { get; set; }
        public virtual ICollection<password> password { get; set; }
    }
}
