//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fkdsr
    {
        public int lsh { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public string xsbid { get; set; }
        public string xsbmc { get; set; }
        public string czy { get; set; }
        public Nullable<decimal> shxj_fss { get; set; }
        public Nullable<decimal> zzsr_fss { get; set; }
        public Nullable<decimal> qtjs_fss { get; set; }
        public Nullable<decimal> hj1_fss { get; set; }
        public Nullable<decimal> dtzz_fss { get; set; }
        public Nullable<decimal> dtqt_fss { get; set; }
        public Nullable<decimal> dtxj_fss { get; set; }
        public Nullable<decimal> zxxj_fss { get; set; }
        public Nullable<decimal> zxzz_fss { get; set; }
        public Nullable<decimal> zxqt_fss { get; set; }
        public Nullable<decimal> qtxj_fss { get; set; }
        public Nullable<decimal> qtzz_fss { get; set; }
        public Nullable<decimal> gzxj_fss { get; set; }
        public Nullable<decimal> gzzz_fss { get; set; }
        public Nullable<decimal> hkxj_fss { get; set; }
        public Nullable<decimal> hkzz_fss { get; set; }
        public Nullable<decimal> hj2_fss { get; set; }
        public Nullable<decimal> hkqt_fss { get; set; }
        public Nullable<decimal> yfxj_fss { get; set; }
        public Nullable<decimal> yfzz_fss { get; set; }
        public Nullable<decimal> yfqt_fss { get; set; }
        public Nullable<decimal> hkhj_fss { get; set; }
        public string bz { get; set; }
        public Nullable<decimal> yfhj_fss { get; set; }
        public Nullable<decimal> dthj_fss { get; set; }
        public Nullable<decimal> zxhj_fss { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public Nullable<decimal> kzhj_fss { get; set; }
        public Nullable<decimal> gzhj_fss { get; set; }
        public string ywlb { get; set; }
        public Nullable<decimal> hkhj_sjs { get; set; }
        public Nullable<decimal> yfhj_sjs { get; set; }
        public Nullable<decimal> dthj_sjs { get; set; }
        public Nullable<decimal> zxhj_sjs { get; set; }
        public Nullable<decimal> kzhj_sjs { get; set; }
        public Nullable<decimal> gzhj_sjs { get; set; }
        public Nullable<decimal> gsdf_sjs { get; set; }
        public Nullable<decimal> gsdf_hk { get; set; }
        public Nullable<decimal> gsdf_yf { get; set; }
        public Nullable<decimal> gsdf_zxf { get; set; }
        public Nullable<decimal> gsdf_dt { get; set; }
        public Nullable<decimal> ycl_fss { get; set; }
        public Nullable<decimal> ycl_sjs { get; set; }
        public Nullable<decimal> ycl_hjs { get; set; }
        public Nullable<decimal> ycl_hjs1 { get; set; }
        public Nullable<decimal> ycl_qt { get; set; }
        public Nullable<decimal> ycl_sr { get; set; }
        public Nullable<decimal> qtfyqt { get; set; }
    }
}
