//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fykzdmx
    {
        public int lsh { get; set; }
        public string fykzdid { get; set; }
        public string lbmc { get; set; }
        public decimal fyje { get; set; }
        public string zph { get; set; }
        public string zymc { get; set; }
        public string xsbid { get; set; }
        public string syy { get; set; }
        public string bz { get; set; }
        public string fzr { get; set; }
        public string flag { get; set; }
        public string pjh { get; set; }
        public string lbbm { get; set; }
        public string skfmc { get; set; }
        public string zybm { get; set; }
        public string jbr { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public string khfy { get; set; }
        public string bmfy { get; set; }
        public string yyy { get; set; }
        public string ywy { get; set; }
        public string sjsid { get; set; }
        public string sjsname { get; set; }
        public string yjkmbm { get; set; }
        public string yjkmmc { get; set; }
        public string kjkmmc { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string clmc { get; set; }
        public string fyqtx { get; set; }
        public string zhid { get; set; }
        public string zhmc { get; set; }
        public string bcfykzdid { get; set; }
        public string ddh { get; set; }
        public string xsdhd_ddh { get; set; }
        public string HkDjlx { get; set; }
    
        public virtual fykzd fykzd { get; set; }
    }
}
