//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fykzd
    {
        public fykzd()
        {
            this.fykzdmx = new HashSet<fykzdmx>();
        }
    
        public string fykzdid { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public string xjzh { get; set; }
        public string zzzh { get; set; }
        public decimal fyje { get; set; }
        public string zph { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public string bz { get; set; }
        public string czy { get; set; }
        public string flag { get; set; }
        public string czlx { get; set; }
        public string dysy { get; set; }
        public string checkingFlag { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string khid_qt { get; set; }
        public string ghsid_qt { get; set; }
        public string sdr { get; set; }
        public Nullable<int> tzMonth { get; set; }
        public Nullable<int> tzyear { get; set; }
        public string fykzdcxid { get; set; }
        public string djlx { get; set; }
        public string spr { get; set; }
        public string sp_flag { get; set; }
        public string sp_sm { get; set; }
    
        public virtual ICollection<fykzdmx> fykzdmx { get; set; }
    }
}
