//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ggxxb
    {
        public string gg { get; set; }
        public Nullable<decimal> cphgl { get; set; }
        public Nullable<decimal> yjl { get; set; }
        public Nullable<decimal> rcl { get; set; }
        public Nullable<decimal> clj { get; set; }
        public Nullable<decimal> clf { get; set; }
        public Nullable<decimal> ccjs { get; set; }
        public Nullable<decimal> zlj { get; set; }
        public Nullable<decimal> zlf { get; set; }
        public Nullable<decimal> zdxj { get; set; }
        public Nullable<decimal> zxdj { get; set; }
        public string pxbm { get; set; }
    }
}
