//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ghsxx
    {
        public string ghsid { get; set; }
        public string ghsmc { get; set; }
        public string tel { get; set; }
        public string bp { get; set; }
        public string sj { get; set; }
        public string lxr { get; set; }
        public string address { get; set; }
        public string yb { get; set; }
        public string pydm { get; set; }
        public string zh { get; set; }
        public string khh { get; set; }
        public string sh { get; set; }
        public string email { get; set; }
        public string ghsqc { get; set; }
        public string ghspj { get; set; }
        public string clghsFlag { get; set; }
        public string ghsjb { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
        public string khFlag { get; set; }
        public string khid { get; set; }
        public string ghsFlag { get; set; }
        public string jsghsid { get; set; }
        public string StopSign { get; set; }
        public string jslx { get; set; }
    }
}
