//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class gsxx
    {
        public string gsmc { get; set; }
        public string tel { get; set; }
        public string bp { get; set; }
        public string sj { get; set; }
        public string lxr { get; set; }
        public string address { get; set; }
        public string yb { get; set; }
        public string lb { get; set; }
        public string khh { get; set; }
        public string zh { get; set; }
        public string sh { get; set; }
        public string id { get; set; }
        public string hy { get; set; }
    }
}
