//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class hshkd
    {
        public string hshkdid { get; set; }
        public string khid { get; set; }
        public Nullable<decimal> hkxj { get; set; }
        public Nullable<decimal> hkzz { get; set; }
        public Nullable<decimal> hksr { get; set; }
        public Nullable<decimal> qt { get; set; }
        public decimal hkje { get; set; }
        public string zph { get; set; }
        public string xsbid { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public string syy { get; set; }
        public string bz { get; set; }
        public string czy { get; set; }
        public string khmc { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> qkzpyk { get; set; }
        public Nullable<System.DateTime> xsrqf { get; set; }
        public Nullable<System.DateTime> xsrqt { get; set; }
        public string sgzphid { get; set; }
        public string czlx { get; set; }
        public string hkxz { get; set; }
        public string xjzh { get; set; }
        public string zzzh { get; set; }
        public string bmid { get; set; }
        public string bmmc { get; set; }
        public string qksgh { get; set; }
        public string ddh { get; set; }
        public string ghsFlag { get; set; }
        public string ghsid { get; set; }
        public string checkingFlag { get; set; }
        public string yxsbid { get; set; }
        public string adFlag { get; set; }
        public Nullable<decimal> hksyje { get; set; }
        public string xsdhdid_ddh { get; set; }
        public Nullable<decimal> skje { get; set; }
        public Nullable<decimal> fqje { get; set; }
        public Nullable<decimal> skfy { get; set; }
        public string khid_dskf { get; set; }
        public string khmc_dskf { get; set; }
        public string yhshkdid { get; set; }
        public string yczlx { get; set; }
        public int lsh { get; set; }
        public string sdr { get; set; }
        public string skzh { get; set; }
        public string HkDjlx { get; set; }
    
        public virtual khxx khxx { get; set; }
    }
}
