//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jhyfmxb
    {
        public int jhyfmxlsh { get; set; }
        public string jhdid { get; set; }
        public string jhyfdid { get; set; }
        public Nullable<System.DateTime> jhrq { get; set; }
        public string yfjsf { get; set; }
        public string ysdw { get; set; }
        public Nullable<decimal> ysdj { get; set; }
        public Nullable<decimal> yssl { get; set; }
        public Nullable<decimal> yf { get; set; }
        public Nullable<decimal> yfjsdj { get; set; }
        public Nullable<decimal> yfjsje { get; set; }
        public string qfh { get; set; }
        public Nullable<decimal> jsce { get; set; }
        public string flag { get; set; }
    
        public virtual jhyfb jhyfb { get; set; }
    }
}
