//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jhyfb
    {
        public jhyfb()
        {
            this.jhyfmxb = new HashSet<jhyfmxb>();
        }
    
        public string jhyfdid { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public string xsbid { get; set; }
        public string yssbm { get; set; }
        public string yssmc { get; set; }
        public Nullable<System.DateTime> fsrqf { get; set; }
        public Nullable<System.DateTime> fsrqt { get; set; }
        public decimal jhyf { get; set; }
        public decimal jsyf { get; set; }
        public Nullable<decimal> sr { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string zph { get; set; }
        public string bz { get; set; }
        public string spr { get; set; }
        public string syy { get; set; }
        public string jsr { get; set; }
        public string czy { get; set; }
        public string sgph { get; set; }
        public string flag { get; set; }
        public string czlx { get; set; }
        public string xjzh { get; set; }
        public string zzzh { get; set; }
        public string khbmid { get; set; }
        public string checkingFlag { get; set; }
    
        public virtual ICollection<jhyfmxb> jhyfmxb { get; set; }
    }
}
