//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jkdsr
    {
        public int lsh { get; set; }
        public Nullable<System.DateTime> rq { get; set; }
        public string xsbid { get; set; }
        public string xsbmc { get; set; }
        public string czy { get; set; }
        public Nullable<decimal> shxj_fss { get; set; }
        public Nullable<decimal> zzsr_fss { get; set; }
        public Nullable<decimal> yszk_fss { get; set; }
        public Nullable<decimal> ysfh_fss { get; set; }
        public Nullable<decimal> qt_fss { get; set; }
        public Nullable<decimal> hj1_fss { get; set; }
        public Nullable<decimal> xsxj { get; set; }
        public Nullable<decimal> xssr_fss { get; set; }
        public Nullable<decimal> xszz { get; set; }
        public Nullable<decimal> xsqk { get; set; }
        public Nullable<decimal> shqk_fss { get; set; }
        public Nullable<decimal> xsys { get; set; }
        public Nullable<decimal> xsqt { get; set; }
        public Nullable<decimal> yuszk_fss { get; set; }
        public Nullable<decimal> qkxj { get; set; }
        public Nullable<decimal> gkdf_fss { get; set; }
        public Nullable<decimal> qkzz { get; set; }
        public Nullable<decimal> qkqt { get; set; }
        public Nullable<decimal> xshj { get; set; }
        public Nullable<decimal> hj2_fss { get; set; }
        public Nullable<decimal> ypyjfss { get; set; }
        public Nullable<decimal> qkhj { get; set; }
        public Nullable<decimal> ysxj { get; set; }
        public Nullable<decimal> yszz { get; set; }
        public Nullable<decimal> ysys { get; set; }
        public Nullable<decimal> ysqt { get; set; }
        public string bz { get; set; }
        public Nullable<decimal> yshj { get; set; }
        public Nullable<System.DateTime> jsrq { get; set; }
        public Nullable<decimal> ypxj { get; set; }
        public string ywlb { get; set; }
        public Nullable<decimal> yphj { get; set; }
        public Nullable<decimal> zpykhj { get; set; }
        public Nullable<decimal> xszpyk { get; set; }
        public Nullable<decimal> qkzpyk { get; set; }
        public Nullable<decimal> yszpyk { get; set; }
        public Nullable<decimal> xssr { get; set; }
        public Nullable<decimal> qksr { get; set; }
        public Nullable<decimal> yssr { get; set; }
        public Nullable<decimal> ypsr { get; set; }
        public Nullable<decimal> ypqt { get; set; }
        public Nullable<decimal> qtxj { get; set; }
        public Nullable<decimal> qtzz { get; set; }
        public Nullable<decimal> srje { get; set; }
        public Nullable<decimal> qthj { get; set; }
        public Nullable<decimal> xsyf { get; set; }
        public Nullable<decimal> xsbyf { get; set; }
        public Nullable<decimal> xsjgf { get; set; }
        public Nullable<decimal> xshk { get; set; }
        public Nullable<decimal> xsqtfy { get; set; }
        public Nullable<decimal> fyhj { get; set; }
        public Nullable<decimal> ypys { get; set; }
        public Nullable<decimal> ypzz { get; set; }
        public Nullable<decimal> qtqt { get; set; }
    }
}
