//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class khxx
    {
        public string khid { get; set; }
        public string khmc { get; set; }
        public string tel { get; set; }
        public Nullable<decimal> bp { get; set; }
        public string sj { get; set; }
        public string lxr { get; set; }
        public string address { get; set; }
        public string yb { get; set; }
        public string pydm { get; set; }
        public string zh { get; set; }
        public string khh { get; set; }
        public string sh { get; set; }
        public string email { get; set; }
        public string khqy { get; set; }
        public string khxz { get; set; }
        public string xzxf { get; set; }
        public string gxjb { get; set; }
        public string gxxf { get; set; }
        public string xqmc { get; set; }
        public string scmc { get; set; }
        public string zlmc { get; set; }
        public string khlx { get; set; }
        public string ywy { get; set; }
        public string xsbmc { get; set; }
        public string jgzc { get; set; }
        public string ProjectName { get; set; }
        public string Developer { get; set; }
        public string ItemAddress { get; set; }
        public string Constructor { get; set; }
        public string Architect { get; set; }
        public string Supervise { get; set; }
        public string NamedConsignee { get; set; }
        public string ShopKeeper { get; set; }
        public string ShopArea { get; set; }
        public string ViewArea { get; set; }
        public string OtherThings { get; set; }
        public string OperationManager { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
        public string jskhid { get; set; }
        public string gllb { get; set; }
        public bool outputTelAndAddress { get; set; }
        public string jsghsid { get; set; }
        public string ghsFlag { get; set; }
        public string stevedoreAddress { get; set; }
        public string stevedorePhoto { get; set; }
        public string companyFullName { get; set; }
        public Nullable<int> arrearDay { get; set; }
        public string stopSign { get; set; }
        public Nullable<decimal> arrearMoney { get; set; }
        public string xsdhdYsSign { get; set; }
        public string zklFlag { get; set; }
        public Nullable<decimal> zkl { get; set; }
        public string KhspdjFlag { get; set; }
        public string QdtsjFlag { get; set; }
        public string yyy { get; set; }
        public string sjs { get; set; }
        public Nullable<System.DateTime> sxrq { get; set; }
        public Nullable<System.DateTime> sxjsrq { get; set; }
        public string sxr { get; set; }
        public string sxczy { get; set; }
    }
}
