//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class password
    {
        public password()
        {
            this.CompetenceSet = new HashSet<CompetenceSet>();
        }
    
        public string czy { get; set; }
        public string gh { get; set; }
        public string jhd { get; set; }
        public string cbtjd { get; set; }
        public string xsd { get; set; }
        public string ypd { get; set; }
        public string tzd { get; set; }
        public string bsd { get; set; }
        public string pdd { get; set; }
        public string hsd { get; set; }
        public string ndd { get; set; }
        public string xsdcj { get; set; }
        public string jhdcj { get; set; }
        public string qtsr { get; set; }
        public string hkyfjsd { get; set; }
        public string fzxfd { get; set; }
        public string fjhyfd { get; set; }
        public string hktzd { get; set; }
        public string cgdd { get; set; }
        public string cjfhd { get; set; }
        public string ztyssd { get; set; }
        public string ztyfjsd { get; set; }
        public string bankck { get; set; }
        public string fykzd { get; set; }
        public string gzb { get; set; }
        public string fytzd { get; set; }
        public string cshmm { get; set; }
        public string xsdhd { get; set; }
        public string yclcgd { get; set; }
        public Nullable<decimal> qked { get; set; }
        public Nullable<int> UserGroupID { get; set; }
        public string CzyXsbAllPowerSign { get; set; }
        public string bz { get; set; }
        public string jgflag { get; set; }
        public Nullable<decimal> zkl { get; set; }
        public Nullable<decimal> fykzjeq { get; set; }
        public string fykzjeq_flag { get; set; }
        public Nullable<decimal> zhwljeq { get; set; }
        public string zhwljeq_flag { get; set; }
        public string gyhkjeq_flag { get; set; }
        public Nullable<decimal> gyhkjeq { get; set; }
        public string mbz { get; set; }
        public Nullable<decimal> ypjeq { get; set; }
        public string ypjeq_flag { get; set; }
        public string jmpw { get; set; }
        public string stopSign { get; set; }
    
        public virtual ICollection<CompetenceSet> CompetenceSet { get; set; }
    }
}
