//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class qtsrmx
    {
        public int lsh { get; set; }
        public string skfbm { get; set; }
        public string qtsrdid { get; set; }
        public string lbmc { get; set; }
        public string zymc { get; set; }
        public decimal je { get; set; }
        public string zph { get; set; }
        public string xsbid { get; set; }
        public string syy { get; set; }
        public string bz { get; set; }
        public string fzr { get; set; }
        public string flag { get; set; }
        public string pjh { get; set; }
        public string lbbm { get; set; }
        public string skfmc { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public string zybm { get; set; }
        public string jbr { get; set; }
        public string sjsid { get; set; }
        public string sjsname { get; set; }
        public string yjkmbm { get; set; }
        public string yjkmmc { get; set; }
        public string kjkmmc { get; set; }
        public string bmfy { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string checkingFlag { get; set; }
    
        public virtual qtsrd qtsrd { get; set; }
    }
}
