//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SdEntities : DbContext
    {
        public SdEntities()
            : base("name=SdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserGroup> UserGroup { get; set; }
        public virtual DbSet<gsxx> gsxx { get; set; }
        public virtual DbSet<CompetenceSet> CompetenceSet { get; set; }
        public virtual DbSet<password> password { get; set; }
        public virtual DbSet<khxx> khxx { get; set; }
        public virtual DbSet<zlb> zlb { get; set; }
        public virtual DbSet<bigDepartment> bigDepartment { get; set; }
        public virtual DbSet<xsbxx> xsbxx { get; set; }
        public virtual DbSet<zyxx> zyxx { get; set; }
        public virtual DbSet<xqxx> xqxx { get; set; }
        public virtual DbSet<spPmlb> spPmlb { get; set; }
        public virtual DbSet<cpxllx> cpxllx { get; set; }
        public virtual DbSet<jldwb> jldwb { get; set; }
        public virtual DbSet<ggxxb> ggxxb { get; set; }
        public virtual DbSet<cpxl> cpxl { get; set; }
        public virtual DbSet<ghsxx> ghsxx { get; set; }
        public virtual DbSet<spfl> spfl { get; set; }
        public virtual DbSet<xsd> xsd { get; set; }
        public virtual DbSet<xsdmx> xsdmx { get; set; }
        public virtual DbSet<spxx> spxx { get; set; }
        public virtual DbSet<fkdsr> fkdsr { get; set; }
        public virtual DbSet<jkdsr> jkdsr { get; set; }
        public virtual DbSet<xsdhd> xsdhd { get; set; }
        public virtual DbSet<xsdhdmx> xsdhdmx { get; set; }
        public virtual DbSet<hshkd> hshkd { get; set; }
        public virtual DbSet<zt_ysd> zt_ysd { get; set; }
        public virtual DbSet<zt_ysdmx> zt_ysdmx { get; set; }
        public virtual DbSet<jhyfb> jhyfb { get; set; }
        public virtual DbSet<jhyfmxb> jhyfmxb { get; set; }
        public virtual DbSet<qtsrd> qtsrd { get; set; }
        public virtual DbSet<qtsrmx> qtsrmx { get; set; }
        public virtual DbSet<zt_hkyfjsd> zt_hkyfjsd { get; set; }
        public virtual DbSet<fykzd> fykzd { get; set; }
        public virtual DbSet<fykzdmx> fykzdmx { get; set; }
    
        public virtual ObjectResult<string> proc_PH(string djlb, string xsbmc, ObjectParameter result)
        {
            var djlbParameter = djlb != null ?
                new ObjectParameter("djlb", djlb) :
                new ObjectParameter("djlb", typeof(string));
    
            var xsbmcParameter = xsbmc != null ?
                new ObjectParameter("xsbmc", xsbmc) :
                new ObjectParameter("xsbmc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("proc_PH", djlbParameter, xsbmcParameter, result);
        }
    }
}
