//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.CompetenceSet = new HashSet<CompetenceSet>();
        }
    
        public int UserGroupID { get; set; }
        public string UserGroupName { get; set; }
    
        public virtual ICollection<CompetenceSet> CompetenceSet { get; set; }
    }
}
