//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xqxx
    {
        public string xqid { get; set; }
        public string xqmc { get; set; }
        public string tel { get; set; }
        public string qyjl { get; set; }
        public string fzrsj { get; set; }
        public string sj { get; set; }
        public string fzr { get; set; }
        public string address { get; set; }
        public string yb { get; set; }
        public string zh { get; set; }
        public string khh { get; set; }
        public string sh { get; set; }
        public string email { get; set; }
        public string qyqc { get; set; }
        public string bz { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
    }
}
