//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xsbxx
    {
        public string xsbid { get; set; }
        public string xsbmc { get; set; }
        public string bz { get; set; }
        public string xsdqz { get; set; }
        public string xsdcd { get; set; }
        public string xsdcsz { get; set; }
        public string ypdqz { get; set; }
        public string ypdcd { get; set; }
        public string ypdcsz { get; set; }
        public string ysdqz { get; set; }
        public string ysdcd { get; set; }
        public string ysdcsz { get; set; }
        public string hkdqz { get; set; }
        public string hkdcd { get; set; }
        public string hkdcsz { get; set; }
        public string hkjsdqz { get; set; }
        public string hkjsdcd { get; set; }
        public string hkjsdcsz { get; set; }
        public string hktzdqz { get; set; }
        public string hktzdcd { get; set; }
        public string hktzdcsz { get; set; }
        public string zxdqz { get; set; }
        public string zxdcd { get; set; }
        public string zxdcsz { get; set; }
        public string jhyfdqz { get; set; }
        public string jhyfdcd { get; set; }
        public string jhyfdcsz { get; set; }
        public string fykzdqz { get; set; }
        public string fykzdcd { get; set; }
        public string fykzdcsz { get; set; }
        public string xsdhdqz { get; set; }
        public string xsdhdcd { get; set; }
        public string xsdhdcsz { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
        public int bigDepartmentID { get; set; }
        public string cwbd { get; set; }
        public string dyxz { get; set; }
        public string cklx { get; set; }
        public string dhjkdqz { get; set; }
        public string dhjkdcd { get; set; }
        public string dhjkdcsz { get; set; }
        public string jgflag { get; set; }
        public Nullable<decimal> bmzkl { get; set; }
        public string bmfzr { get; set; }
        public Nullable<decimal> fzrzkl { get; set; }
        public string stopsign { get; set; }
    }
}
