//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xsd
    {
        public xsd()
        {
            this.xsdmx = new HashSet<xsdmx>();
        }
    
        public string xsdid { get; set; }
        public string xsbid { get; set; }
        public Nullable<System.DateTime> xsrq { get; set; }
        public string khid { get; set; }
        public string yyy { get; set; }
        public string ywy { get; set; }
        public string zl { get; set; }
        public string shr { get; set; }
        public string syy { get; set; }
        public string kpy { get; set; }
        public string fzr { get; set; }
        public string czy { get; set; }
        public decimal zje { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public Nullable<decimal> ys { get; set; }
        public Nullable<decimal> yus { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string zph { get; set; }
        public Nullable<decimal> sr { get; set; }
        public string flag { get; set; }
        public string khmc { get; set; }
        public string sgzphid { get; set; }
        public string bz { get; set; }
        public string xscj { get; set; }
        public Nullable<decimal> xscjl { get; set; }
        public string bcxsdid { get; set; }
        public string xqid { get; set; }
        public string scid { get; set; }
        public string xqmc { get; set; }
        public string scmc { get; set; }
        public Nullable<decimal> zzl { get; set; }
        public Nullable<decimal> xszpyk { get; set; }
        public string czlx { get; set; }
        public string hshkdid { get; set; }
        public string ejkh { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string bmid { get; set; }
        public string bmmc { get; set; }
        public string ddh { get; set; }
        public Nullable<decimal> fy_yf { get; set; }
        public string y_ysr { get; set; }
        public Nullable<decimal> fy_byf { get; set; }
        public string y_byr { get; set; }
        public Nullable<decimal> fy_jgf { get; set; }
        public string y_jgs { get; set; }
        public Nullable<decimal> fy_hk { get; set; }
        public string y_hkr { get; set; }
        public Nullable<decimal> hkl { get; set; }
        public Nullable<decimal> fy_qt { get; set; }
        public Nullable<decimal> fy_fyhj { get; set; }
        public string dnddh { get; set; }
        public string spjsbz { get; set; }
        public string xsjetzr { get; set; }
        public string fkr { get; set; }
        public string ysbm { get; set; }
        public string ysdh { get; set; }
        public string driver { get; set; }
        public string sjdh { get; set; }
        public string xh { get; set; }
        public string fh { get; set; }
        public string bz2 { get; set; }
        public Nullable<System.DateTime> fhrq { get; set; }
        public string zzzh { get; set; }
        public Nullable<decimal> kpze { get; set; }
        public string jskhid { get; set; }
        public string ysjzbz { get; set; }
        public string sjsid { get; set; }
        public string shdd { get; set; }
        public string fw { get; set; }
        public string ch { get; set; }
        public string print_bz { get; set; }
        public string cwflag { get; set; }
        public string wdthSign { get; set; }
        public string cwSaveSign { get; set; }
        public string xstime { get; set; }
        public string sdr { get; set; }
        public string sgddh { get; set; }
        public Nullable<int> printCount { get; set; }
        public Nullable<decimal> zzkl { get; set; }
        public Nullable<decimal> bzze { get; set; }
        public Nullable<decimal> ssze { get; set; }
        public Nullable<decimal> qk { get; set; }
        public Nullable<decimal> ydj { get; set; }
        public Nullable<decimal> xjzje { get; set; }
        public Nullable<decimal> kdqzsyk { get; set; }
        public Nullable<decimal> wshxsys { get; set; }
        public Nullable<decimal> kdhzsyk { get; set; }
        public Nullable<decimal> khxyd { get; set; }
        public Nullable<decimal> kdqddyk { get; set; }
        public Nullable<decimal> kdhddyk { get; set; }
        public Nullable<decimal> czyqx { get; set; }
        public Nullable<decimal> kdqssyk { get; set; }
        public Nullable<decimal> kqjye { get; set; }
        public Nullable<decimal> hkwse { get; set; }
        public string mpssm { get; set; }
        public Nullable<decimal> kdqssyk_dd { get; set; }
        public Nullable<decimal> kdhssyk_dd { get; set; }
        public Nullable<decimal> hkwse_dd { get; set; }
        public Nullable<decimal> wshxsys_dd { get; set; }
        public string fyzczh { get; set; }
        public string fysh_flag { get; set; }
        public string fy_sdr { get; set; }
        public string fy_czy { get; set; }
        public Nullable<decimal> hjzje { get; set; }
        public Nullable<decimal> zczje { get; set; }
        public string bz3 { get; set; }
        public string bz_czy { get; set; }
        public Nullable<decimal> kzl { get; set; }
        public Nullable<decimal> SZzl { get; set; }
        public Nullable<decimal> Szl { get; set; }
        public Nullable<decimal> CzL { get; set; }
        public Nullable<System.DateTime> QkHkrq { get; set; }
        public Nullable<System.DateTime> QkQrRq { get; set; }
        public string QkQrCzy { get; set; }
        public string QkWkjsr { get; set; }
        public string QkJqFlag { get; set; }
        public Nullable<decimal> jxtcl { get; set; }
        public string TcCzy { get; set; }
    
        public virtual xsbxx xsbxx { get; set; }
        public virtual ICollection<xsdmx> xsdmx { get; set; }
    }
}
