//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xsdhdmx
    {
        public int lsh { get; set; }
        public string xsdhdid { get; set; }
        public string kqid { get; set; }
        public string spid { get; set; }
        public string dw { get; set; }
        public string color { get; set; }
        public decimal xssl { get; set; }
        public Nullable<decimal> xs { get; set; }
        public Nullable<decimal> zhps { get; set; }
        public Nullable<int> zhxs { get; set; }
        public decimal xsje { get; set; }
        public decimal xsdj { get; set; }
        public Nullable<decimal> dwkg { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> dwcb { get; set; }
        public Nullable<decimal> xsxj { get; set; }
        public Nullable<decimal> xsxl { get; set; }
        public Nullable<System.DateTime> ylrq { get; set; }
        public string thbz { get; set; }
        public string czlx { get; set; }
        public Nullable<int> ylts { get; set; }
        public Nullable<decimal> dbj { get; set; }
        public Nullable<decimal> zdxj { get; set; }
        public Nullable<decimal> kpe { get; set; }
        public Nullable<decimal> zkl { get; set; }
        public string fsmc { get; set; }
        public string bz { get; set; }
        public string hshkdid { get; set; }
        public string spjsbz { get; set; }
        public Nullable<int> yxsdhdmxlsh { get; set; }
        public Nullable<decimal> tsxsdj { get; set; }
        public string NoStandardSign { get; set; }
        public string fkcFlag { get; set; }
        public string cjddh { get; set; }
        public string NewNodeName { get; set; }
        public string OldNodeName { get; set; }
        public string Useage { get; set; }
        public string xshFlag { get; set; }
        public string fhr { get; set; }
        public string bhcolor { get; set; }
        public string mxbz { get; set; }
        public Nullable<decimal> xsxl1 { get; set; }
        public Nullable<decimal> xsxl2 { get; set; }
        public Nullable<decimal> yxsdj { get; set; }
        public string CgspFlag { get; set; }
    
        public virtual xsdhd xsdhd { get; set; }
    }
}
