//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class xsdhd
    {
        public xsdhd()
        {
            this.xsdhdmx = new HashSet<xsdhdmx>();
        }
    
        public string xsdhdid { get; set; }
        public Nullable<System.DateTime> dhrq { get; set; }
        public string ywy { get; set; }
        public string yyy { get; set; }
        public string zlmc { get; set; }
        public string zph { get; set; }
        public Nullable<decimal> sr { get; set; }
        public decimal dhje { get; set; }
        public Nullable<decimal> qt { get; set; }
        public Nullable<decimal> yus { get; set; }
        public Nullable<decimal> ys { get; set; }
        public Nullable<decimal> zz { get; set; }
        public Nullable<decimal> xj { get; set; }
        public string czy { get; set; }
        public string fzr { get; set; }
        public string syy { get; set; }
        public string kpy { get; set; }
        public Nullable<decimal> zpyk { get; set; }
        public string sgzph { get; set; }
        public string bz { get; set; }
        public string flag { get; set; }
        public string xqmc { get; set; }
        public string khid { get; set; }
        public string scmc { get; set; }
        public Nullable<decimal> zyj { get; set; }
        public Nullable<decimal> zzl { get; set; }
        public string xsbid { get; set; }
        public string thbz { get; set; }
        public string czlx { get; set; }
        public string ejkh { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public string bmid { get; set; }
        public string bmmc { get; set; }
        public Nullable<decimal> hksr { get; set; }
        public Nullable<decimal> hkss { get; set; }
        public string jskhid { get; set; }
        public string zzzh { get; set; }
        public string psrq { get; set; }
        public Nullable<int> pscs { get; set; }
        public string sjs { get; set; }
        public Nullable<decimal> fyyf { get; set; }
        public Nullable<decimal> fy_byf { get; set; }
        public Nullable<decimal> fy_jgf { get; set; }
        public Nullable<decimal> fy_hk { get; set; }
        public Nullable<decimal> hkl { get; set; }
        public string hshkdid { get; set; }
        public Nullable<decimal> fy_qt { get; set; }
        public string spjsbz { get; set; }
        public Nullable<decimal> fy_fyhj { get; set; }
        public string y_ysr { get; set; }
        public string y_byr { get; set; }
        public string y_jgs { get; set; }
        public string y_hkr { get; set; }
        public string fkr { get; set; }
        public string xsbz { get; set; }
        public string xdhrq { get; set; }
        public string ddh { get; set; }
        public string dzdh { get; set; }
        public Nullable<decimal> skfyje { get; set; }
        public Nullable<decimal> skje { get; set; }
        public Nullable<decimal> fqje { get; set; }
        public Nullable<decimal> yfye { get; set; }
        public string dskf { get; set; }
        public string hshkdid_dhxj { get; set; }
        public string hshkdid_dsdhxj { get; set; }
        public string xsdhdid_ys { get; set; }
        public string khid_dskf { get; set; }
        public string sdr { get; set; }
        public Nullable<int> printCount { get; set; }
        public string print_bz { get; set; }
        public string skzh { get; set; }
        public Nullable<decimal> zzkl { get; set; }
        public Nullable<decimal> bzze { get; set; }
        public Nullable<decimal> ssze { get; set; }
        public Nullable<decimal> xjzje { get; set; }
        public string mpssm { get; set; }
        public string mbz { get; set; }
        public Nullable<System.DateTime> QkHkrq { get; set; }
        public Nullable<System.DateTime> QkQrRq { get; set; }
        public string QkQrCzy { get; set; }
        public string QkWkjsr { get; set; }
        public string QkJqFlag { get; set; }
        public Nullable<decimal> jxtcl { get; set; }
        public string TcCzy { get; set; }
    
        public virtual ICollection<xsdhdmx> xsdhdmx { get; set; }
    }
}
