//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlb
    {
        public string zldm { get; set; }
        public string zlmc { get; set; }
        public string xjbm { get; set; }
        public string xjmc { get; set; }
        public string sjbm { get; set; }
        public string sjmc { get; set; }
        public string zdxjbm { get; set; }
        public string zdxjmc { get; set; }
        public string dbbm { get; set; }
        public string dbmc { get; set; }
        public string only_flag { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
        public bool PrintCheck { get; set; }
        public string cxbz { get; set; }
        public string xjbm1 { get; set; }
        public string xjmc1 { get; set; }
        public string sjbm1 { get; set; }
        public string sjmc1 { get; set; }
        public string zdxjbm1 { get; set; }
        public string zdxjmc1 { get; set; }
        public string dbbm1 { get; set; }
        public string dbmc1 { get; set; }
        public Nullable<int> bighellId { get; set; }
        public string tsxjbm { get; set; }
        public string tsxjmc { get; set; }
        public string tssjbm { get; set; }
        public string tssjmc { get; set; }
        public string tsdbbm { get; set; }
        public string tsdbmc { get; set; }
        public string tszdxjbm { get; set; }
        public string tszdxjmc { get; set; }
        public string tsSign { get; set; }
        public Nullable<int> tsjgbm { get; set; }
        public string tsjgmc { get; set; }
        public string sanitationFlag { get; set; }
        public string ShowPriceSign { get; set; }
    }
}
