//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zt_hkyfjsd
    {
        public string hkyfdid { get; set; }
        public int lsh { get; set; }
        public string xsbid { get; set; }
        public Nullable<System.DateTime> fkrq { get; set; }
        public string ghsid { get; set; }
        public string xsbmc { get; set; }
        public string ghsmc { get; set; }
        public string fkxz { get; set; }
        public decimal fkje { get; set; }
        public string fkfs { get; set; }
        public string syy { get; set; }
        public string pzh { get; set; }
        public string czy { get; set; }
        public Nullable<decimal> xj { get; set; }
        public Nullable<decimal> zz { get; set; }
        public Nullable<decimal> qt { get; set; }
        public string zph { get; set; }
        public Nullable<decimal> sr { get; set; }
        public string flag { get; set; }
        public string spr { get; set; }
        public string sgzphid { get; set; }
        public string bz { get; set; }
        public Nullable<decimal> jyzje { get; set; }
        public string xjzh { get; set; }
        public string zzzh { get; set; }
        public string checkingFlag { get; set; }
        public string spr_yh { get; set; }
        public string sp_flag { get; set; }
        public string sp_sm { get; set; }
    }
}
