//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zt_ysdmx
    {
        public int lsh { get; set; }
        public string fh { get; set; }
        public string ysdid { get; set; }
        public string xh { get; set; }
        public string bz { get; set; }
        public string spid { get; set; }
        public string czy { get; set; }
        public string color { get; set; }
        public Nullable<decimal> bszl { get; set; }
        public Nullable<int> zhxs { get; set; }
        public Nullable<decimal> zhps { get; set; }
        public string ghsid { get; set; }
        public string ghsmc { get; set; }
        public Nullable<decimal> xs { get; set; }
        public decimal yssl { get; set; }
        public string dw { get; set; }
        public Nullable<decimal> dwkg { get; set; }
        public Nullable<decimal> xyf { get; set; }
        public Nullable<decimal> dwyf { get; set; }
        public string flag { get; set; }
        public string dhbz { get; set; }
        public Nullable<decimal> rksl { get; set; }
        public string fhdid { get; set; }
        public Nullable<int> fhdmxlsh { get; set; }
        public string cjddh { get; set; }
        public string ccdh { get; set; }
        public string bcysdid { get; set; }
        public Nullable<decimal> fhwysl { get; set; }
    
        public virtual zt_ysd zt_ysd { get; set; }
    }
}
