//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zt_ysd
    {
        public zt_ysd()
        {
            this.zt_ysdmx = new HashSet<zt_ysdmx>();
        }
    
        public string cjdh { get; set; }
        public string ysdid { get; set; }
        public Nullable<System.DateTime> ysrq { get; set; }
        public string yssmc { get; set; }
        public string ysdw { get; set; }
        public decimal yssl { get; set; }
        public decimal ysdj { get; set; }
        public decimal yf { get; set; }
        public Nullable<decimal> ztyf { get; set; }
        public string cch { get; set; }
        public string bz { get; set; }
        public Nullable<decimal> sjzl { get; set; }
        public Nullable<decimal> bszl { get; set; }
        public string flag { get; set; }
        public Nullable<decimal> dwyf { get; set; }
        public int lsh { get; set; }
        public string czy { get; set; }
        public Nullable<System.DateTime> yjdhrq { get; set; }
        public string jsbz { get; set; }
        public Nullable<decimal> yfjsdj { get; set; }
        public Nullable<decimal> yfjsje { get; set; }
        public string czlx { get; set; }
        public string mddmc { get; set; }
        public string xsbid { get; set; }
        public string DHBZ { get; set; }
        public string djlx { get; set; }
        public string ysdcxid { get; set; }
        public Nullable<decimal> cjdt { get; set; }
    
        public virtual ICollection<zt_ysdmx> zt_ysdmx { get; set; }
    }
}
