//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class zyxx
    {
        public string zyid { get; set; }
        public string name { get; set; }
        public string bmid { get; set; }
        public string sex { get; set; }
        public string zw { get; set; }
        public string tel { get; set; }
        public string bp { get; set; }
        public string sj { get; set; }
        public string sfz { get; set; }
        public string address { get; set; }
        public string yj { get; set; }
        public string yb { get; set; }
        public string kjkm { get; set; }
        public string yyy { get; set; }
        public string ywy { get; set; }
        public string syy { get; set; }
        public string kpy { get; set; }
        public string cgy { get; set; }
        public string shr { get; set; }
        public string spr { get; set; }
        public string pym { get; set; }
        public string pxbm { get; set; }
        public string stopSign { get; set; }
        public Nullable<decimal> xye { get; set; }
        public string xyeflag { get; set; }
    }
}
