//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sd.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResx() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sd.UI.Properties.MsgResx", typeof(MsgResx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加失败，请检查字段后重试。 的本地化字符串。
        /// </summary>
        internal static string add_fail {
            get {
                return ResourceManager.GetString("add_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功！ 的本地化字符串。
        /// </summary>
        internal static string add_success {
            get {
                return ResourceManager.GetString("add_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入必填项！ 的本地化字符串。
        /// </summary>
        internal static string check_pk_null {
            get {
                return ResourceManager.GetString("check_pk_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除该数据？ 的本地化字符串。
        /// </summary>
        internal static string confrim_delete {
            get {
                return ResourceManager.GetString("confrim_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该数据已经被删除。 的本地化字符串。
        /// </summary>
        internal static string delete_check {
            get {
                return ResourceManager.GetString("delete_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除本单？ 的本地化字符串。
        /// </summary>
        internal static string delete_confirm {
            get {
                return ResourceManager.GetString("delete_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败，别的表是否正在使用，请检查字段后重试。 的本地化字符串。
        /// </summary>
        internal static string delete_fail {
            get {
                return ResourceManager.GetString("delete_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功！ 的本地化字符串。
        /// </summary>
        internal static string delete_success {
            get {
                return ResourceManager.GetString("delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合计金额不对，请重修该单子 的本地化字符串。
        /// </summary>
        internal static string hjzje_error {
            get {
                return ResourceManager.GetString("hjzje_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该单号不存在，请重新输入 的本地化字符串。
        /// </summary>
        internal static string input_id_null {
            get {
                return ResourceManager.GetString("input_id_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请正确输入金额— 的本地化字符串。
        /// </summary>
        internal static string input_money_chk {
            get {
                return ResourceManager.GetString("input_money_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现金+转账+应收 ！= 实付金额，请修改 的本地化字符串。
        /// </summary>
        internal static string input_money_ssze {
            get {
                return ResourceManager.GetString("input_money_ssze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请稍后，登录中。。。 的本地化字符串。
        /// </summary>
        internal static string login_btn_logining {
            get {
                return ResourceManager.GetString("login_btn_logining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称或密码不正确！ 的本地化字符串。
        /// </summary>
        internal static string login_error_001 {
            get {
                return ResourceManager.GetString("login_error_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string login_txt_pwd {
            get {
                return ResourceManager.GetString("login_txt_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string login_txt_user {
            get {
                return ResourceManager.GetString("login_txt_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名或密码不能为空！ 的本地化字符串。
        /// </summary>
        internal static string login_txt_user_pwd {
            get {
                return ResourceManager.GetString("login_txt_user_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本单已经打印，不能重复打印！ 的本地化字符串。
        /// </summary>
        internal static string print_already {
            get {
                return ResourceManager.GetString("print_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到打印机 的本地化字符串。
        /// </summary>
        internal static string print_noprinter {
            get {
                return ResourceManager.GetString("print_noprinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本单已审核 的本地化字符串。
        /// </summary>
        internal static string review_already {
            get {
                return ResourceManager.GetString("review_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核失败，请重新审核 的本地化字符串。
        /// </summary>
        internal static string review_faild {
            get {
                return ResourceManager.GetString("review_faild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 审核完了 的本地化字符串。
        /// </summary>
        internal static string review_success {
            get {
                return ResourceManager.GetString("review_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 满足条件的结果为【0】，请重新输入 的本地化字符串。
        /// </summary>
        internal static string search_result_null {
            get {
                return ResourceManager.GetString("search_result_null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本单已审核，无法修改！ 的本地化字符串。
        /// </summary>
        internal static string update_chk_reviewed {
            get {
                return ResourceManager.GetString("update_chk_reviewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败，该数据可能已被删除，请检查字段后重试。 的本地化字符串。
        /// </summary>
        internal static string update_fail {
            get {
                return ResourceManager.GetString("update_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功！ 的本地化字符串。
        /// </summary>
        internal static string update_success {
            get {
                return ResourceManager.GetString("update_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 销售明细为空，请重新输入 的本地化字符串。
        /// </summary>
        internal static string xsdmx_null {
            get {
                return ResourceManager.GetString("xsdmx_null", resourceCulture);
            }
        }
    }
}
